#!/usr/bin/env python3
from faker import Faker

from email_service.domain.consumer import Config
from email_service.domain.consumer import EmailRequest
from email_service.domain.publisher import EmailPublisher

fake = Faker()
config = Config()
publisher = EmailPublisher(host=config.kafka_host, port=config.kafka_port)
for i in range(20):
    request = EmailRequest(
        from_address=config.username,
        to_address=config.username,
        text=fake.text(),
        html=None,
        subject=f"[{i}] Performance test",
    )
    publisher.publish(request)
